# Generated by Django 5.1.4 on 2024-12-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usn', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('fathers_name', models.CharField(max_length=100)),
                ('mothers_name', models.CharField(max_length=100)),
                ('fathers_phone', models.CharField(max_length=15)),
                ('mothers_phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('aadhar_number', models.CharField(max_length=12, unique=True)),
                ('fee_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
