# Generated by Django 5.1.4 on 2025-03-06 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_transactions_options_transactions_received_by_and_more'),
        ('school', '0004_feecategory_feetransaction_feeitem_student_and_more'),
    ]

    operations = [
    ]
