# Generated by Django 5.1.4 on 2025-03-06 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_merge_20250306_0719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='feeitem',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='feetransaction',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='feetransaction',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='amount',
            new_name='total_amount',
        ),
        migrations.CreateModel(
            name='PaymentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('tuition', 'Tuition'), ('transport', 'Transport'), ('book', 'Book'), ('uniform', 'Uniform'), ('competitive', 'Competitive'), ('celebrations', 'Celebrations'), ('admission', 'Admission'), ('application', 'Application'), ('others', 'Others')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Required for Others category', null=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='school.transactions')),
            ],
            options={
                'verbose_name_plural': 'Payment Categories',
            },
        ),
        migrations.DeleteModel(
            name='FeeCategory',
        ),
        migrations.DeleteModel(
            name='FeeItem',
        ),
        migrations.DeleteModel(
            name='FeeTransaction',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
