# Generated by Django 5.1.6 on 2025-03-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0006_remove_feeitem_category_remove_feeitem_transaction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactions",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="registration_number",
            field=models.CharField(
                blank=True,
                help_text="Student's unique registration number",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="Fee_Due",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
