# Generated by Django 5.1.6 on 2025-03-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0007_transactions_time_userprofile_registration_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
    ]
