# Generated by Django 5.1.4 on 2025-03-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParentCorner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="parent_corner/"),
                ),
                ("link", models.URLField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("announcements", "Announcements"),
                            ("forms", "Forms & Documents"),
                            ("guidelines", "Guidelines"),
                            ("other", "Other Resources"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Parent Corner Resource",
                "verbose_name_plural": "Parent Corner Resources",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentPortal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="student_portal/"
                    ),
                ),
                ("link", models.URLField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("academic", "Academic Resources"),
                            ("forms", "Forms & Documents"),
                            ("notices", "Notices"),
                            ("other", "Other Resources"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Student Portal Resource",
                "verbose_name_plural": "Student Portal Resources",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="ParentResource",
        ),
        migrations.DeleteModel(
            name="StudentResource",
        ),
        migrations.AlterModelOptions(
            name="academiccalendar",
            options={
                "ordering": ["start_date"],
                "verbose_name": "Academic Calendar Event",
                "verbose_name_plural": "Academic Calendar Events",
            },
        ),
        migrations.AlterModelOptions(
            name="latestupdate",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Latest Update",
                "verbose_name_plural": "Latest Updates",
            },
        ),
        migrations.RenameField(
            model_name="academiccalendar",
            old_name="date",
            new_name="start_date",
        ),
        migrations.RenameField(
            model_name="latestupdate",
            old_name="content",
            new_name="description",
        ),
        migrations.AddField(
            model_name="academiccalendar",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="academiccalendar",
            name="is_important",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="latestupdate",
            name="category",
            field=models.CharField(
                choices=[
                    ("news", "News"),
                    ("events", "Events"),
                    ("achievements", "Achievements"),
                    ("announcements", "Announcements"),
                ],
                default="news",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="latestupdate",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
